name: deploy-auth

on:
    push:
        branches:
            - master
        paths:
            - 'auth/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd auth && docker build -t austinmie/auth .
            - run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            - run: docker push austinmie/auth
            - name: Check if DIGITAL_ACCESS_SECRET is set
              run: |
                if [ -z "${{ secrets.DIGITAL_ACCESS_SECRET }}" ]; then
                  echo "❌ Secret is NOT set"
                  exit 1
                else
                  echo "✅ Secret is set"
                fi
            - uses: digitalocean/action-doctl@v2
              env:
                DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITAL_ACCESS_SECRET }}
            - run: doctl kubernetes cluster kubeconfig save ticketing
            - run: kubectl rollout restart deployment auth-depl
            - run: docker logout
