name: deploy-expiration

on:
  push:
    branches:
      - master
    paths:
      - "expiration/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t austinmie/expiration .
      - run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker push austinmie/expiration
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment expiration-depl
      - run: docker logout
